# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: llevasse <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/18 09:37:55 by llevasse          #+#    #+#              #
#    Updated: 2022/08/18 09:55:31 by llevasse         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror *.c -o ft_display_file 

clean:
	rm *.o

fclean:
	rm *.o
	rm ft_display_file
